name: Notion Update Check

on:
  schedule:
    - cron: '* * */1 * *'  # 15分ごと
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install requests
      - name: Run notifier
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}
          ISSUE_NUMBER: ${{ secrets.ISSUE_NUMBER }}
        run: python check_notion.py
